image:
  repository: europe-southwest1-docker.pkg.dev/challenge-moonpay/challenge-moonpay/devops-challenge-app
  tag: "sha-1d37a7c"

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  NODE_ENV: "development"

db:
  host: "postgresql-dev.dev.svc.cluster.local"
  name: "moonpay"
  user: "moonpay"