image:
  repository: europe-southwest1-docker.pkg.dev/challenge-moonpay/challenge-moonpay/devops-challenge-app
  tag: "none"

replicaCount: 1

service:
  type: LoadBalancer
  port: 80

env:
  NODE_ENV: "development"