image:
  repository: europe-southwest1-docker.pkg.dev/challenge-moonpay/challenge-moonpay/devops-challenge-app
  tag: "sha-a76fc8c"

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  NODE_ENV: "production"

db:
  host: "postgresql-prod.prod.svc.cluster.local"
  name: "moonpay"
  user: "moonpay"