apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: "<YOUR_GITHUB_REPO_URL_HERE>"
  username: "<YOUR_GITHUB_USERNAME_HERE>"
  password: "<YOUR_GITHUB_PAT_HERE>"