# Default values for moonpay-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

migrations:
  enabled: true

image:
  repository: europe-southwest1-docker.pkg.dev/challenge-moonpay/challenge-moonpay/devops-challenge-app
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  NODE_ENV: "production"