apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "moonpay-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "moonpay-app.selectorLabels" . | nindent 6 }}
    spec:
      {{- if .Values.migrations.enabled }}
      initContainers:
        - name: run-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_PRISMA_URL
              value: "postgresql://{{ .Values.db.user }}:$(DB_PASSWORD)@{{ .Values.db.host }}:5432/{{ .Values.db.name }}"
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
      {{- end }}
      containers:
        - name: nextjs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_PRISMA_URL
              value: "postgresql://{{ .Values.db.user }}:$(DB_PASSWORD)@{{ .Values.db.host }}:5432/{{ .Values.db.name }}"
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}