postgresql:
  architecture: standalone

  primary:
    persistence:
      enabled: true
      size: 8Gi

  passwordUpdateJob:
    enabled: false
  auth:
    username: moonpay
    database: moonpay
    existingSecret: db-credentials
    secretKeys:
      userPasswordKey: password