postgresql:
  architecture: standalone

  primary:
    persistence:
      enabled: true
      size: 8Gi

  passwordUpdateJob:
    enabled: true
  auth:
    username: moonpay
    database: moonpay
    existingSecret: db-credentials      # Tell Bitnami to read from our secret
    secretKeys:
      userPasswordKey: password