argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      accounts.ci-bot: apiKey

    rbac:
      policy.csv: |
        p, role:ci-bot, applications, get,    */*, allow
        p, role:ci-bot, applications, sync,   */*, allow
        p, role:ci-bot, applications, update, */*, allow
        g, ci-bot, role:ci-bot
      policy.default: role:readonly

  server:
    service:
      type: LoadBalancer

argocd-apps:
  applicationsets:
    cluster-apps-dev:
      namespace: argocd
      generators:
        - git:
            repoURL: "https://github.com/jdaniel-garcia/devops-challenge.git"
            revision: main
            directories:
              - path: charts/*

      template:
        metadata:
          name: '{{path.basename}}-dev'
        spec:
          project: default
          source:
            repoURL: "https://github.com/jdaniel-garcia/devops-challenge.git"
            targetRevision: main
            path: '{{path}}'
            helm:
              valueFiles:
                - 'values/dev.yaml'
          destination:
            server: "https://kubernetes.default.svc"
            namespace: dev
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true

    cluster-apps-prod:
      namespace: argocd
      generators:
        - git:
            repoURL: "https://github.com/jdaniel-garcia/devops-challenge.git"
            revision: main
            directories:
              - path: charts/*
      template:
        metadata:
          name: '{{path.basename}}-prod'
        spec:
          project: default
          source:
            repoURL: "https://github.com/jdaniel-garcia/devops-challenge.git"
            targetRevision: main
            path: '{{path}}'
            helm:
              valueFiles:
                - 'values/prod.yaml'
          destination:
            server: "https://kubernetes.default.svc"
            namespace: prod
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true