argo-cd:
  configs:
    params:
      server.insecure: true

  server:
    service:
      type: LoadBalancer

# values.yaml
argocd-apps:
  applicationsets:
    cluster-apps:
          namespace: argocd
          generators:
            - matrix:
                generators:
                  - git:
                      repoURL: "https://github.com/jdaniel-garcia/devops-challenge.git"
                      revision: main
                      directories:
                        - path: charts/*
                  - list:
                      elements:
                        - env: dev
                        - env: prod
          template:
            metadata:
              name: '{{path.basename}}-{{env}}'
            spec:
              project: default
              source:
                repoURL: "https://github.com/jdaniel-garcia/devops-challenge.git"
                targetRevision: main
                path: '{{path}}'
                helm:
                  valueFiles:
                    - 'values-{{env}}.yaml'
              destination:
                server: "https://kubernetes.default.svc"
                namespace: '{{env}}'
              syncPolicy:
                automated:
                  prune: true
                  selfHeal: true
                syncOptions:
                  - CreateNamespace=true